services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: tala1234
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/weather_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/weather_app
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0